music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<song>[-\w]+)/$', views.song_detail, name='song_detail'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<song>[-\w]+)/$', views.song_lyrics, name='song_lyrics'),
    url(r'^breaking_free_lyrics/(?P<song_id>[0-9]+)$', views.breaking_free, name='breaking_free'),
    url(r'^god_like_you_lyrics/(?P<song_id>[0-9]+)$', views.god_like, name='god_like')
]

themusic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls', namespace='music', app_name='music'))

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


class Song(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    songFile = models.FileField(upload_to='mysongs')
    artist = models.CharField(max_length=250)
    song_logo = models.ImageField(upload_to='myimages', default='')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('music:song_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug]
                       )


class DailyQuotes(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    artist = models.CharField(max_length=250)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class BibleQuotes(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    artist = models.CharField(max_length=250)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    song = models.ForeignKey(Song, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.song)


class Lyric(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('music:song_lyrics',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug]
                       )


music/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import DailyQuotes, BibleQuotes, Song, Lyric
from .forms import CommentForm
from django.contrib import messages


def index(request):
    daily = DailyQuotes.objects.all()
    bible = BibleQuotes.objects.all()
    song = Song.objects.all()
    lyrics = Lyric.objects.all()

    return render(request, 'music/index.html', {'daily': daily, 'bible': bible, 'song': song, 'lyrics': lyrics})


def song_detail(request, year, month, day, song):
    song = get_object_or_404(Song, slug=song,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day
                             )

    comments = song.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.song = song
            new_comment.save()
            messages.success(request, 'Your comment has been successfully added')
        else:
            messages.error(request, 'There was an error trying to add your comment')
    else:
        comment_form = CommentForm()

    return render(request, 'music/song_detail.html', {'songs': song, 'comment_form': comment_form, 'comments': comments})


def song_lyrics(request, year, month, day, lyric):
    lyric = get_object_or_404(Lyric, slug=lyric,
                              publish__year=year,
                              publish__month=month,
                              publish__day=day
                              )
    return render(request, 'music/song_lyrics.html', {'lyric': lyric})


def breaking_free(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    return render(request, 'music/breaking_free.html', {'song': song})


def god_like(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    return render(request, 'music/god_like.html', {'song': song})

music/templates/base.html
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
      {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">

    <meta charset="UTF-8">
    <title>{%block title%} {%endblock%}</title>
</head>
<body id="bod" data-spy="scroll" data-target=".navbar" data-offset="100">
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-default navbar-fixed-top">
                {% load static %}
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-target="#navB" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {% load static %}
                    <a class="navbar-brand logo" href="{% url 'music:index' %}">
                        MKD Music Crew
                    </a>
                </div>

                <div class="navbar-collapse collapse" id="navB">
                     <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="#playlist"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a>
                        </li>
                        <li><a href="#mkda">MKD Artistes</a> </li>
                     </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#lyric">Song Lyrics</a> </li>
                        <li><a href="#contact">Contact Us</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    {%block content%}

    {%endblock%}

    {%load static%}
    <script src="{%static 'music/bootstrap/js/jquery.min.js'%}"></script>
    <script src="{%static 'music/bootstrap/js/bootstrap.min.js'%}"></script>

</body>
</html>

music/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
      {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">

    <meta charset="UTF-8">
    <title>{%block title%} {%endblock%}</title>
</head>
<body id="bod" data-spy="scroll" data-target=".navbar" data-offset="100">
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-target="#navB" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {% load static %}
                    <a class="navbar-brand logo" href="{% url 'music:index' %}">
                        MKD Music Crew
                    </a>
                </div>
            </nav>
        </div>
    </div>

    {%block content%}

    {%endblock%}

    {%load static%}
    <script src="{%static 'music/bootstrap/js/jquery.min.js'%}"></script>
    <script src="{%static 'music/bootstrap/js/bootstrap.min.js'%}"></script>

</body>
</html>

music/templates/music/breaking_free.html
{%extends 'base2.html'%}

{%block title%} Breaking Free Lyrics{%endblock%}

{%block content%}
    <div class="container">
        <h3 class="uni">
            <span class="glyphicon glyphicon-headphones" aria-hidden="True"></span> {{song.title}}
        </h3>
         <audio controls class="music">
            <source src="{{song.songFile.url}}" type="audio/ogg">
            <source src="{{song.songFile.url}}" type="audio/mpeg">
            <source src="{{song.songFile.url}}" type="audio/wav">
         </audio>
    </div>
    <br>
    <div  class="container lyrical">
        [Mugonchez]
          <br>
            yeah yeah
          <br>
        Oooooooooh Danny B, Dero Kim, Moses Everybody
          <br>
        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of sa...
          <br>
          <br>

        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of satan
          <br>
          <br>

        [Mugonchez]
          <br>
        Lord give me
          <br>
        All your love is all I need
          <br>
        Make me all you want of me
          <br>
        Am at peace with you ma lord
          <br>
        Every way you show me
          <br>
        I will never lose it now
          <br>
        I dedicate my life to you
          <br>
        Coz I will never be the same again
          <br>
          <br>

        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of sa...
          <br>

        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of satan
          <br>
          <br>

        [Danny B]
          <br>
        Umenitoa low kwenye zangu struggles
          <br>
        Coz without you singetoka kwenye scandals
          <br>
        Ways of man zilikuwa zani strangle
          <br>
        But now nko fiti you alone ndo stand on
          <br>
        Jehova jire kwangu mi ndiye candle
          <br>
        Shida zikikam mi nazi handle
          <br>
        In Christ kila kitu ninaweza handle
          <br>
        That's why ninakam ninasema thank you
          <br>
          <br>

        [Mugonchez]
          <br>
        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of sa...
          <br>
        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of satan
          <br>
          <br>

        [Trapper_Kimdrick]
          <br>
        Yeah Mose spoken breaking free from chains of Satan
          <br>
        Yeah dear God help me yeah my daily activities
          <br>
        Its not my will but the Lord will lift me
          <br>
        Tryna flow lyrics coz ain't gonna critics
          <br>
        He's gonna mix evil like a blender
          <br>
        He's gonna fix your issues call it spanner
          <br>
        Yeah anyone can praise the Lord
          <br>
        Coz He got no restrictions
          <br>
        People gonna tease you but the lord got you
          <br>
        Pata neno coz God ndio wetu
          <br>
          <br>

        [Mugonchez]
          <br>
        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of sa...
          <br>

        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of satan
          <br>
          <br>

        Everybody knows
          <br>
        Am breaking off these chains
          <br>
        Am moving on to God
          <br>
        He's the only one I need
          <br>
        Am holding on to him
          <br>
        He's holding on me
          <br>
        Am never letting go....yeah
          <br>

        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of sa...
          <br>
          <br>

        Everybody knows am going far
          <br>
        Everybody knows am setting high
          <br>
        Everybody knows am breaking free from chains of satan
          <br>

    </div>

{%endblock%}

music/templates/music/form_template.html
{% for field in comment_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <div class="col-sm-4">
            <label class="control-label">{{field.label_tag}}</label>
        </div>
        <div class="col-sm-10">
            {{field}}
        </div>
    </div>
{%endfor%}

music/templates/music/god_like.html
{%extends 'base2.html'%}

{%block title%}God Like You Lyrics{%endblock%}

{%block content%}
     <div class="container">
        <h3 class="uni">
            <span class="glyphicon glyphicon-headphones" aria-hidden="True"></span> {{song.title}}
        </h3>

         <audio controls class="music">
            <source src="{{song.songFile.url}}" type="audio/ogg">
            <source src="{{song.songFile.url}}" type="audio/mpeg">
            <source src="{{song.songFile.url}}" type="audio/wav">
         </audio>
    </div>
    <br>
    <div  class="container lyrical" >

            [Mugonchez]
          <br>
        I have never seen a God like you
          <br>
        You got me up now am feeling so high
          <br>
        You my hope, for my life
          <br>
        I can't live a day without you Lord
          <br>
          <br>

        Everyday on ma knees I do bow (I do bow)
          <br>
        Give thanks to ma God that is how (That is how)
          <br>
        I always do ma things I mean look at now (look at now)
          <br>
        I can sing, I can rap coz my God is wow!
          <br>
          <br>

        [Mugonchez]
          <br>
        Ain't gonna fear (fear)
          <br>
        My God is always near
          <br>
        Wanna shout to the world to get me loud & clear
          <br>
        I praise from ma heart coz He reign,coz He reign
          <br>
        coz He reign, coz He reign, coz He reign (ooh Lord)
          <br>
        I sing for you (yeah)
          <br>
        Do ma prayers to you
          <br>
        Never be ashamed coz I live for you
          <br>
        I say no more tears (tears)
          <br>
        No more pain for me...yeah
          <br>
        uuuuh lalaa...
          <br>
          <br>

        [Trapper_Kimdrick]
          <br>
        Nimetoka mbali miles
          <br>
        Naenda mbali miles
          <br>
        Najua kila step Jehovah ndio ameni-hold till now (X2)
          <br>
        Sio kiherhere buh am just speaking my mind (mind)
          <br>
        Just trynna make it clear that we have sinned ata ameniskia
          <br>
        Nikijua nime-take a long way now am here
          <br>
        Take a wrong path ndio utajua life ni kuumia (what!)
          <br>
        Take a wrong path ndio utajua life ni kuumia (oh yeah)
          <br>
          <br>

        Vipi vipi bradhe, siste, mum and dad
          <br>
        kila siku, wiki, miezi, miaka tume-seek word
          <br>
        kila njia, kila path word ndio guard
          <br>
        Buh I'mma sure one day tutakuwa on same line
          <br>
        Sheto is just a shadow to our minds li-like a Dejavu
          <br>
        Tusifanye sins ziwe kam-kama Dejavu
          <br>
        Usi-fume nkibonga hivi sidai kuona mashavu
          <br>
        Wasee most wamebonda tumezoea kuona mashavu
          <br>
          <br>

        [Mugonchez]
          <br>
        I have never seen a God like you
          <br>
        You got me up now am feeling so high
          <br>
        You my hope, for my life
          <br>
        I can't live a day without you Lord
          <br>
          <br>

        Everyday on ma knees I do bow (I do bow)
          <br>
        Give thanks to ma God that is how (That is how)
          <br>
        I always do ma things I mean look at now (look at now)
          <br>
        I can sing, I can rap coz my God is wow!
          <br>
          <br>

        [Danny B]
          <br>
        To my God I do, Dedication
          <br>
        Coz all I am is under His, Supervision
          <br>
        Never tremble  His protection is, on me
          <br>
        This ain't just a song but a true, Story
          <br>
        Coz I write about my life, History
          <br>
        You go live in a storey-building
          <br>
        You don't have to worry
          <br>
        You have to bend low on your knees
          <br>
        To get a bungalow, all your needs
          <br>
          <br>

        Surrender all to God
          <br>
        Let Him control your odds
          <br>
        Come to God with thanks giving in your heart
          <br>
        Unto Him give the glory...everyday
          <br>
        Say unto daddy, give the glory...everyday
          <br>
          <br>

        [Vajom]
          <br>
        Must have gone numb from my head to my toe
          <br>
        Must have gone numb you better ask my bro
          <br>
        Must have gone numb for the type of guys I roll with
          <br>
        Must have gone numb coz they make me go banana
          <br>
        Ok I love it, I love it when I go numb
          <br>
        They say I have it
          <br>
        Sleeping on the couch
          <br>
        Wake up see the sunny give thanks to Almighty (yeah) X2
          <br>
          <br>

        [Mugonchez]
          <br>
        I have never seen a God like you
          <br>
        You got me up now am feeling so high
          <br>
        You my hope, for my life
          <br>
        I can't live a day without you Lord
          <br>
          <br>

        Everyday on ma knees I do bow (I do bow)
          <br>
        Give thanks to ma God that is how (That is how)
          <br>
        I always do ma things I mean look at now (look at now)
          <br>
        I can sing, I can rap coz my God is wow!
          <br>

    </div>

{%endblock%}

music/templates/music/index.html
<!--Inheriting from the base template-->
{% extends 'base.html'%}

{%block title%} Home {%endblock%}

{%block content%}

<!--load static files from the static directory-->
    {% load static %}

<!-- Cover photo & Blog section-->
    <div class="container">
        <div class="col-md-8">
            <img src="{% static 'music/img/mkd4.jpg' %}" class="img-responsive heit">
        </div>

        <div class="col-md-4 sideB">
            <h3 id="Iq">Blog</h3>
            <h3 id="iq2">Latest News</h3>
         <!--retrieving data from the database using a for loop-->
            {%for quote in daily%}
                <p id="quote">
                    {{quote.body}}
                </p>
                <p class="pub">
                    Posted {{quote.publish}} by {{quote.artist}}
                </p>
            {%endfor%}
            <br>
            <h3 id="Ib">Events</h3>
            <p id="quot">
                {%for quot in bible%}
                {{quot.body}}
            </p>
            <br>
            <br>
            <p class="pub">
                Posted {{quot.publish}} by {{quot.artist}}
            </p>
            {%endfor%}
        </div>
    </div>
    <br>

<!--About us section-->
    <div class="container">
        <div class="col-sm-5 mkd">
            <h3 class="hu">About Us</h3>
        </div>
    </div>
    <br>
    <div class="container">
        <p id="pras">
            <b>MKD</b> is an upcoming music group currently based in Kibra. Our main aim is to spread the word of God and inspire
            people through our music. <b>MKD</b> is composed of four people who are devoted to the group to ensure the main
            aim is achieved; Moses Mugoya aka <b>Mugonchez</b> is the vocalist, Derrick Kimaisi aka <b>Trapper_
            Kimdrick</b> is a rapper, Daniel Wandera aka <b>Danny B</b> is a rapper too and finally George Juma aka
            <b>Vajom</b> who is also a rapper. <b>MKD</b> started in the year 2015 consisting of three members; <b>Mugonchez</b>,
            <b>Kimdrick</b> and <b>Danny B</b>. The group was named after the three members as initials of the first letter
            of their names,(<b>M</b>ugonchez <b>K</b>imdrick <b>D</b>anny B). The group grew and now it has four members including
            Vajom.
        </p>

    </div>
    <br>

<!--Song playlist section-->
  <div class="container">
      <div class="col-sm-5 mkd">
        <h3 class="hu" id="playlist">Songs Playlist</h3>
      </div>
      <br>
      <br>
      <br>
      <p class="more">These are the songs that we have recorded so far but there are more to come.</p>

      <!--retrieving songs from the database using a for loop-->
      {%for son in song%}
            <h3 >
                <a id="songs" href="{{son.get_absolute_url}}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>  {{son.title}}
                </a>
            </h3>
            <p class="counts">
                <a href="{{son.get_absolute_url}}">
                     <img src="{%static 'music/img/comment.png'%}" style="width:34px;height:34px;border:0;">
                     {{son.comments.count}} comment{{ son.comments.count|pluralize }}
                </a>
            </p>
      {%endfor%}
  </div>
  <br>

<!--MKD artistes section-->
  <div class="container">
      <div class="col-sm-5 mkd" >
          <h3 class="hu" id="mkda">MKD Artistes</h3>
      </div>
  </div>
  <br>
  <div class="container">
      <div class="row">
           <p class="more" id="left">Currently, these are the artistes of MKD music group. We hope the number will grow as
               time goes by because we want to grow a music empire.
           </p>
          <br>
          {%load static%}
          <section class="col-sm-3">
              <img src="{% static 'music/img/mugonchez.jpg'%}" class="img-rounded img-responsive hi">
              <h3 class="name">Mugonchez</h3>
              <p class="art">
                  Moses Mugoya aka Mugonchez is a humble and God fearing man. He is saved and a singer in the MKD music group.He likes
                  singing and dancing and sometimes you wll hear him rap. Mugonchez is a student at Meru University
                  of Science and Technology taking a bachelor's degree in Computer Science. When he is not singing, you
                  will find him coding programs, he is also interested in technology. He is the designer and developer
                  of this website. He believes he'll make the greatest developer.
              </p>
          </section>

          <section class="col-sm-3">
              <img src="{%static 'music/img/dannyB.jpg'%}" class="img-rounded img-responsive hi">
              <h3 class="name">Danny B</h3>
              <p class="art">
                  Dani-el Wandera aka Danny B is an artiste who does mostly inspirational songs. He is born again and
                  accepts Jesus Christ as his personal LORD and saviour. He is a rapper in the MKD music group but
                  a times he also sings. He believes in being the best though not perfect as man is to error. Danny B
                  likes travelling a lot. He believes and has faith that someday he'll make the best Engineer.
              </p>
          </section>

          <section class="col-sm-3">
              <img src="{%static 'music/img/trapper.jpg'%}" class="img-rounded img-responsive hi">
              <h3 class="name">Trapper_Kimdrick</h3>
              <p class="art">
                  Derrick Kimaisi is a God fearing person and a rapper based on inspiration in the MKD music group.
                  Trapper_Kimdrick is his preferably stage name. He loves freestyles. Trapper is a Plant Ecologist in
                  the making at Jomo Kenyatta University of Agriculture and Technology (JKUAT), Juja main campus. He is
                  reachable at social media handles at Trapper_Kimdrick, be it youtube, twitter, facebook or Instagram.
              </p>
          </section>

          <section class="col-sm-3">
              <img src="{% static 'music/img/vajom.jpg'%}" class="img-rounded img-responsive hi">
              <h3 class="name">Vajom</h3>
              <p class="art">
                  George Juma aka Vajom is one of the most coolest and God fearing person. Currently he is a member of
                  the best music group in town,MKD. He is a rapper and also a singer. When he is not in the studio, you
                  will find him in class teaching. He likes interacting with his students encouraging them so that they
                  make it someday in life.
              </p>
          </section>
      </div>
  </div>
  <br>

<!--Song Lyrics section-->
  <div class="container">
      <div class="col-sm-5 mkd">
          <h3 class="hu" id="lyric">Song Lyrics</h3>
      </div>
  </div>

  <div class="container">
          {% for songs in song%}
            {% if songs.slug == "breaking-free" %}
                <h3>
                    <a class="lyrics" href="{% url 'music:breaking_free'  songs.id%}">
                         <span class="glyphicon glyphicon-cd" aria-hidden="True"></span> {{songs.title}}
                    </a>
                </h3>
                <p class="count">
                    [Mugonchez]
                      <br>
                        yeah yeah
                      <br>
                    Oooooooooh Danny B, Dero Kim, Moses Everybody
                      <br>
                    Everybody knows am going far
                      <br>
                    Everybody knows am setting high
                      <br>
                    Everybody knows am breaking free from chains of sa...
                      <br>
                    <h4 class="create">Click on the song to view the full lyrics</h4>
                </p>
            {% elif songs.slug == "god-like-you" %}
                <h3>
                    <a  class="lyrics" href="{% url 'music:god_like'  songs.id%}">
                         <span class="glyphicon glyphicon-cd" aria-hidden="True"></span> {{songs.title}}
                    </a>
                </h3>
                <p class="count">
                    [Mugonchez]
                      <br>
                    I have never seen a God like you
                      <br>
                    You got me up now am feeling so high
                      <br>
                    You my hope, for my life
                      <br>
                    I can't live a day without you Lord...
                      <br>
                    <h4 class="create">Click on the song to view the full lyrics</h4>
                </p>
           {% else %}
            <h3>
                 <a class="lyrics" href="#">
                         <span class="glyphicon glyphicon-cd" aria-hidden="True"></span> {{songs.title}}
                 </a>
            </h3>

            <h4 class="create">The lyrics for Exactly are not yet out but will be available soon</h4>
            {%endif%}
          {%endfor%}
  </div>

<!--footer section-->
  <div id="footer">
      <h3 id="contact">Contact Us</h3>
      <p>Email: mosesmugoya31@gmail.com</p>
      <p>Tel  : +254705784902 - Mugonchez</p>
      <p>Tel  : +254724032653 - Danny B</p>
      <P>Tel  : +254797178909 - Vajom</P>
      <p>Tel  : +254791255862 - Trapper_Kimdrick</p>

      &copy; 2017 MKDMusic.com All Rights Reserved
        <br>
        <br>
      <p id="dev">Designed and developed by Mugonchez</p>

  </div>

{%endblock%}

music/templates/music/song_lyrics.html
{%extends 'base.html'%}
{%block title%}Song lyrics{%endblock%}

{%block content%}


{%endblock%}